# Generated by Django 2.0.4 on 2019-12-12 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawl_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='获取时间')),
                ('crawl_status', models.BooleanField(default=False, verbose_name='获取状态')),
                ('run_method', models.CharField(max_length=200, verbose_name='调用方法')),
                ('run_parma', models.CharField(max_length=200, verbose_name='调用参数')),
            ],
            options={
                'verbose_name': '获取日志',
                'verbose_name_plural': '获取日志',
            },
        ),
        migrations.CreateModel(
            name='ProxyIP',
            fields=[
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('ip', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='IP')),
                ('port', models.PositiveIntegerField(verbose_name='端口号')),
                ('speed', models.FloatField(blank=True, default=0.0, null=True, verbose_name='连接速度')),
                ('supplier', models.CharField(default='', max_length=50, verbose_name='提供方')),
                ('address', models.CharField(default='', max_length=100, verbose_name='归属地')),
                ('proxy_type', models.CharField(default='HTTP', max_length=5, verbose_name='代理类型')),
            ],
            options={
                'verbose_name': '代理IP池',
                'verbose_name_plural': '代理IP池',
            },
        ),
        migrations.CreateModel(
            name='ServerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_user_name', models.CharField(default='', max_length=200, verbose_name='访问用户名')),
                ('request_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='访问时间')),
                ('request_ip', models.GenericIPAddressField(protocol='ipv4', verbose_name='访问IP')),
                ('request_function', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='访问功能')),
                ('request_param', models.TextField(blank=True, default='', null=True, verbose_name='请求参数')),
                ('response_data', models.TextField(blank=True, default='', null=True, verbose_name='返回数据')),
            ],
            options={
                'verbose_name': '访问日志',
                'verbose_name_plural': '访问日志',
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='操作时间')),
                ('operation_detail', models.CharField(default='', max_length=200, verbose_name='操作详情')),
                ('operation_before', models.CharField(default='', max_length=250, verbose_name='操作前')),
                ('operation_after', models.CharField(default='', max_length=250, verbose_name='操作后')),
            ],
            options={
                'verbose_name': '用户日志',
                'verbose_name_plural': '用户日志',
            },
        ),
    ]
