# Generated by Django 2.0.4 on 2019-12-12 17:58

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('crawl_platform', models.CharField(max_length=50, verbose_name='获取平台')),
                ('company_name', models.CharField(max_length=100, verbose_name='企业名称')),
                ('company_type', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='企业性质')),
                ('company_province', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='企业省份')),
                ('company_city', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='企业城市')),
                ('company_address', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='企业地址')),
                ('company_employ_max', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='员工数低值')),
                ('company_employ_min', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='员工数高值')),
                ('company_stage', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='发展阶段')),
                ('company_industry', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='所属行业')),
                ('company_advantage', models.TextField(blank=True, default='', null=True, verbose_name='竞争优势')),
                ('company_invest_institution', models.TextField(blank=True, default='', null=True, verbose_name='投资机构')),
                ('company_website', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='企业官网')),
                ('company_description', models.TextField(blank=True, default='', null=True, verbose_name='企业描述')),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
            },
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('job_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False, verbose_name='职位ID')),
                ('update_time', models.DateField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('crawl_platform', models.CharField(max_length=50, verbose_name='获取平台')),
                ('refresh_date', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='刷新日期')),
                ('publish_date', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='发布日期')),
                ('is_valid_now', models.BooleanField(default=True, verbose_name='当前是否有效')),
                ('company_name', models.CharField(default='', max_length=100, verbose_name='公司名称')),
                ('job_title', models.CharField(default='', max_length=50, verbose_name='职位名称')),
                ('job_department', models.CharField(default='', max_length=50, verbose_name='职位部门')),
                ('job_rank', models.CharField(default='', max_length=50, verbose_name='职位级别')),
                ('job_summary', models.TextField(blank=True, default='', null=True, verbose_name='职位概述')),
                ('job_province', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='工作省份')),
                ('job_city', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='工作城市')),
                ('job_district', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='行政区')),
                ('job_address', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='工作地址')),
                ('job_work_year_min', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='经验低值')),
                ('job_work_year_max', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='经验高值')),
                ('job_degree', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='学历要求')),
                ('job_language', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='语言要求')),
                ('job_major', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='专业要求')),
                ('job_age_min', models.PositiveIntegerField(default=18, verbose_name='年龄低值')),
                ('job_age_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='年龄高值')),
                ('job_hours_per_day', models.PositiveIntegerField(default=8, verbose_name='天工作时长')),
                ('job_days_per_week', models.PositiveIntegerField(default=5, verbose_name='周工作天数')),
                ('job_salary_min', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='月薪低值')),
                ('job_salary_max', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='月薪高值')),
                ('job_welfare', models.TextField(blank=True, default='', null=True, verbose_name='福利待遇')),
                ('job_type', models.CharField(blank=True, default='全职', max_length=20, null=True, verbose_name='职位性质')),
                ('job_advantage', models.TextField(blank=True, default='', null=True, verbose_name='职位优势')),
                ('job_require', models.TextField(blank=True, default='', null=True, verbose_name='职位要求')),
                ('job_responsibilities', models.TextField(blank=True, default='', null=True, verbose_name='职位职责')),
                ('job_url', models.TextField(validators=[django.core.validators.URLValidator()], verbose_name='职位链接')),
                ('job_email', models.CharField(default='', max_length=50, verbose_name='职位邮箱')),
                ('job_response_ratio', models.FloatField(blank=True, default=0.0, null=True, verbose_name='回复率')),
            ],
            options={
                'verbose_name': '岗位详情',
                'verbose_name_plural': '岗位详情',
            },
        ),
        migrations.CreateModel(
            name='RecruitHistory',
            fields=[
                ('summary_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False, verbose_name='汇总id')),
                ('parse_date', models.CharField(default='', max_length=20, verbose_name='获取日期')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('crawl_platform', models.CharField(max_length=50, verbose_name='获取平台')),
                ('recruit_job_title', models.CharField(max_length=50, verbose_name='职位名称')),
                ('recruit_job_num', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='招聘岗位数量')),
                ('recruit_company_num', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='招聘公司数量')),
                ('salary_min_avg', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='月薪低值均值')),
                ('salary_max_avg', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='月薪高值均值')),
                ('work_year_min_mode', models.PositiveIntegerField(blank=True, null=True, verbose_name='经验低值众数')),
                ('work_year_max_mode', models.PositiveIntegerField(blank=True, null=True, verbose_name='经验高值众数')),
                ('hours_per_day_mode', models.PositiveIntegerField(blank=True, null=True, verbose_name='天工作时长众数')),
                ('days_per_week_mode', models.PositiveIntegerField(blank=True, null=True, verbose_name='周工作天数众数')),
            ],
            options={
                'verbose_name': '招聘历史',
                'verbose_name_plural': '招聘历史',
            },
        ),
        migrations.CreateModel(
            name='UrlPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('platform', models.CharField(default='', max_length=250, verbose_name='招聘平台')),
                ('category', models.CharField(default='', max_length=250, verbose_name='链接类别')),
                ('prefix', models.CharField(default='', max_length=250, verbose_name='前缀')),
                ('parameter', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='参数')),
                ('sample', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='样例')),
            ],
            options={
                'verbose_name': '链接模式',
                'verbose_name_plural': '链接模式',
            },
        ),
    ]
